// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';

// ... This section below, unsure if this is where it needs to be?

await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
);
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo97SbJUl2ZZXsXpX-oLDEg_sACoBBcsQ',
    appId: '1:546223906141:android:89cbe92b3133a3f4f9dcb4',
    messagingSenderId: '546223906141',
    projectId: 'eventsplatform-6b54e',
    storageBucket: 'eventsplatform-6b54e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpvCmGvwSrXo2v09p_8wsWEu5rJ5gBSXQ',
    appId: '1:546223906141:ios:87c6e9847d098005f9dcb4',
    messagingSenderId: '546223906141',
    projectId: 'eventsplatform-6b54e',
    storageBucket: 'eventsplatform-6b54e.firebasestorage.app',
    iosBundleId: 'com.notetakingforeggs.eventsPlatformFrontend',
  );
}
